# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('metric', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
