# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metric',
            new_name='name',
        ),
    ]
